language: python
python:
    - "2.7"
before_install:
    - echo -e "machine github.com\n  login $CI_TOKEN" >> ~/.netrc
    - docker build -t codal-build --build-arg AUTH_TOKEN=$CI_TOKEN --build-arg GIT_COMMIT="HEAD" --build-arg GIT_URL="https://github.com/LabAixBidouille-STM32/codal.git" https://github.com/LabAixBidouille-STM32/codal-docker.git
    - docker run -itd -w /home/codal/codal --name codal-running codal-build:latest /bin/bash
script:
    - docker exec codal-running python build.py https://github.com/LabAixBidouille-STM32/codal-stm32-iot-node#${TRAVIS_COMMIT}
notifications:
    email:
        recipients:
            - codal-build@labaixbidouille.com
        on_success: never
        on_failure: always
        
